config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/show'
  get 'bookings/new'
  get 'bookings/create'
  get 'bookings/show'
  get 'travels/index'
  get 'travels/show'
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :travels, only: [:index, :show] do
    resources :reviews, only: [:index, :new, :create, :show]
  end
  resources :bookings
end

app/models/agency.rb
class Agency < ApplicationRecord
  has_many :travels, dependent: :destroy
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :travel
  belongs_to :user
  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :travel
  belongs_to :user
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :agency
  has_many :bookings, dependent: :destroy
  has_many :reviews
  validates :price, presence: true, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: :new
  before_action :set_travel, only: :new

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save!
      redirect_to booking_path(@booking.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :travel_id, :user_id)
  end

  def set_user
    @user = User.find_by(first_name: "John")
  end

  def set_travel
    @travel = Travel.find(params[:format])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user, only: :new
  before_action :set_travel, only: %i[new create]

  def index
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.travel = @travel
    if @review.save!
      redirect_to travel_review_path(@travel, @review)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_travel
    @travel = Travel.find(params[:travel_id])
  end

  def set_user
    @user = User.find_by(first_name: "John")
  end

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def index
    @travels = Travel.all
  end

  def show
    @travel = Travel.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for @booking do |f| %>
    <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.hidden_field "travel_id", :value => @travel.id %>
    <%= f.hidden_field "user_id", :value => @user.id %>
    <%= f.submit "Confirm booking", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <%= " Starts on #{@booking.start_date}" %>
  </div>
  <div class="row">
    <%= " Ends on #{@booking.end_date}" %>
  </div>
  <div class="row">
    <%= " Destination: #{@booking.travel.name}" %>
  </div>
  <div class="row">
    <%= " Price: #{@booking.travel.price}" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolTravel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="title">
    <h1>Welcome to coolTravel!</h1>
  </div>
  <div class="button-container">
    <div class="btn btn-nav">
      <%= link_to "Go to travels", travels_path %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for [@travel, @review] do |f| %>
    <%= f.input :rating, :collection => 1..5 %>
    <%= f.input :comment %>
    <%= f.hidden_field "user_id", :value => @user.id %>
    <%= f.submit "Post review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/travels/index.html.erb
<div class="container">
  <h1>Here are today's available travels</h1>
  <div class="row">
    <% @travels.each do |travel| %>
      <div>
        <%= link_to "#{travel.name} / ", travel_path(travel) %>
        <%= "#{travel.description} / " %>
        <%= "#{travel.price}€ / " %>
        <%= link_to "Write review", new_travel_review_path(travel.id) %>
      </div>
    <% end %>
  </div>
</div>

app/views/travels/show.html.erb
<div class="container">
  <div class="row">
    <%= "#{@travel.name}" %>
  </div>
  <div class="row">
    <%= "#{@travel.description}" %>
  </div>
  <div class="row">
    <%= "#{@travel.price}€" %>
  </div>
  <div class="row">
    <div class="btn">
      <%= link_to "Book", new_booking_path(@travel.id) %>
    </div>
  </div>
</div>